# Flat structure - keys at root level
MONGO_URI = "mongodb+srv://hassaanshshid7_db_user:LPaYt5q1u8C1d2vE@cluster0.6qlyvyj.mongodb.net/"
OPENWEATHER_API_KEY = "394e28afe4c40dea97f96139625ddfbc"
LATITUDE = 24.8607
LONGITUDE = 67.0011
CITY = "Karachi"
COUNTRY = "PK"
MODEL_PATH = "models/best_model.pkl"